module.exports = {
  out: './docs/',
  readme: 'README.md',
  name: 'Node integrations for Oso Cloud',
  includes: './',
  exclude: [
    '**/test/**/*',
    '**/*.js',
    '**/cjs/**/*',
    '**/esm/**/*',
    '**/build/**/*',
    '**/packages/typescript/**/*',
    '**/packages/eslint-*/**/*',
  ],
  mode: 'modules',
  excludeExternals: true,
  includeDeclarations: true,
  includeVersion: true,
  excludeNotExported: true,
  excludePrivate: true,
};
