name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - name: Install dependencies and build packages
        run: |
          yarn
          yarn build
      - name: Set up .npmrc
        run: echo '//registry.npmjs.org/:_authToken=${secrets.NPM_AUTH_TOKEN_UNCOMMONCENSE_EXP_20240416}' > .npmrc
      - name: Version and publish
        run: yarn lerna publish --yes ${{github.event.inputs.version}}
