name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.ts"
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - name: Install dependencies
        run: |
          yarn
          yarn build:types
      - name: Lint
        run: |
          yarn lint
          yarn fmtcheck
      - name: Test
        run: yarn test
